### ISSUE TITLE
Addressed time4j dependency is not available via central maven

### ISSUE THREAD

**Issue by DivineThreepwood** [pholthau/rst-utils#2]
```
No versions available for net.time4j:time4j-core:jar:[4.28,) within specified range
```
Please make sure the defined version is available to allow an independent rst-utils build.

**Comment by pholthaus** [comment]
The version was outdated and probably dropped from central maven. There's an updated release available (0.1.1) inclduding a fixed dependency. See c97e6c48709067880c379b4327cbabc5be8b5d7d

**Comment by MenoData** [comment]
Maven search shows that the newer versions v4.28 or later all exist:

https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22net.time4j%22%20AND%20a%3A%22time4j-core%22

@pholthau I vaguely remember that there was once a build problem with v4.27.x. Maybe you consider to update your dependency to <time4j.version>[4.28,5.0)</time4j.version> or similar (this would actually grab v4.34, soon v4.35).

**Comment by DivineThreepwood** [comment]
@MenoData thanks for the hint. I created an issue (csra/rst-utils#1) on csra/rst-util because this fork is not supported anymore.

**Comment by pholthaus** [comment]
If you're going to upgrade the range, please also file a pull request here. Thanks for the heads up!
